{% set name = "opentelemetry-distro" %}
{% set version = "0.58b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_distro-{{ version }}.tar.gz
  sha256: ef993c845c11fd156046a96e5ffe1ecfe33f7282fa6149cf9decb26ff8716666

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.58b0
    - opentelemetry-sdk ~=1.13
    # - opentelemetry-exporter-otlp ==1.30.0
    # - opentelemetry-exporter-otlp ==1.31.0
    # - opentelemetry-exporter-otlp ==1.31.1
    # - opentelemetry-exporter-otlp ==1.32.0
    # - opentelemetry-exporter-otlp ==1.32.1
    # - opentelemetry-exporter-otlp ==1.33.0
    # - opentelemetry-exporter-otlp ==1.33.1
    # - opentelemetry-exporter-otlp ==1.34.0
    # - opentelemetry-exporter-otlp ==1.34.1
    # - opentelemetry-exporter-otlp ==1.35.0
    # - opentelemetry-exporter-otlp ==1.36.0
    # - opentelemetry-exporter-otlp ==1.37.0

test:
  imports:
    - opentelemetry.distro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/opentelemetry-distro/
  summary: OpenTelemetry Python Distro
  license: 'Apache-2.0'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - goatmale
