{% set name = "opentelemetry-distro" %}
{% set version = "0.52b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_distro-{{ version }}.tar.gz
  sha256: 18d65f16c42c11969784c6007bcf159f6cb1fb27c91e39e78b8de34ffef4c1d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.52b0
    - opentelemetry-sdk ~=1.13
    # - opentelemetry-exporter-otlp ==1.30.0
    # - opentelemetry-exporter-otlp ==1.31.0

test:
  imports:
    - opentelemetry.distro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/opentelemetry-distro/
  summary: OpenTelemetry Python Distro
  license: 'Apache-2.0'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - goatmale
