{% set name = "opentelemetry-distro" %}
{% set version = "0.49b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_distro-{{ version }}.tar.gz
  sha256: 1bafa274f9e83baa0d2a5d47ed02caffcf9bcca60107b389b145400d82b07513

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-sdk >=1.13,<2.dev0

test:
  imports:
    - opentelemetry.distro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/opentelemetry-distro/
  summary: OpenTelemetry Python Distro
  license: 'Apache-2.0'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - goatmale
