{% set name = "opentelemetry-distro" %}
{% set version = "0.45b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_distro-{{ version }}.tar.gz
  sha256: 81864219f1ec5656973ef42074d27772b3e510c1bcfff09bf34f0c447251a867

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==0.44b0
    - opentelemetry-sdk >=1.13,<2.dev0

test:
  imports:
    - opentelemetry.distro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/opentelemetry-distro/
  summary: OpenTelemetry Python Distro
  license: 'Apache-2.0'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - goatmale
